replicaCount: 1

image:
  repository: paprickar/hcloud-pricing-exporter
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

podAnnotations: { }

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: { }
  hosts:
    - host: chart-example.local
  tls: [ ]

secret:
  create: true
  token:
  reference:
    name:
    key:

serviceMonitor:
  create: false
  interval:
  labels:
  scrapeTimeout:

relabeling:
    enabled: true
    regex: .*


resources: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }

container:
  command: ["./run"]
  args: [""]